import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AllProvider } from "@/shared/contexts";
import { Footer } from "@/shared/components/Footer";
import { ContainerMain } from "@/shared/components/Main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AllProvider>
          <ContainerMain>{children}</ContainerMain>
          <Footer />
        </AllProvider>
      </body>
    </html>
  );
}
